name: "build"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: |
        yarn
        yarn all
