name: "test"
on:
  pull_request:
  issues:
  push:
    branches:
      - master
      - 'releases/*'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: |
        yarn
        yarn build:pack
    - uses: ./
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
